// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace xampl.Models.Documents;

public partial class DocumentList
{
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public short Position { get; set; }

    public int DocumentId { get; set; }

    public virtual Document Document { get; set; }

    public virtual ICollection<DocumentListItem> DocumentListItems { get; set; } = new List<DocumentListItem>();
}