// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace xampl.Models.Documents;

public partial class Document
{
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    public string Title { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<DocumentList> DocumentLists { get; set; } = new List<DocumentList>();

    public virtual ICollection<DocumentNote> DocumentNotes { get; set; } = new List<DocumentNote>();
}