// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace xampl.Models.Documents;

/// <summary>
/// Store main user data
/// </summary>
public partial class User
{
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Email { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Password { get; set; }

    public string Source { get; set; }

    public virtual ICollection<Document> DocumentCreatedByNavigations { get; set; } = new List<Document>();

    public virtual ICollection<Document> DocumentLastUpdatedByNavigations { get; set; } = new List<Document>();
}