// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace xampl.Models;

public partial class DocumentList
{
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    public List<int> ListItems { get; set; }

    public short Position { get; set; }

    public virtual User CreatedByNavigation { get; set; }
}