// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace xampl.Models;

/// <summary>
/// Store main user data
/// </summary>
public partial class User
{
    public long Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }
}