// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace xampl.Models;

public partial class xamplContext : DbContext
{
    public xamplContext(DbContextOptions<xamplContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Document> Documents { get; set; }

    public virtual DbSet<DocumentList> DocumentLists { get; set; }

    public virtual DbSet<DocumentListItem> DocumentListItems { get; set; }

    public virtual DbSet<DocumentNote> DocumentNotes { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresEnum("auth", "aal_level", new[] { "aal1", "aal2", "aal3" })
            .HasPostgresEnum("auth", "code_challenge_method", new[] { "s256", "plain" })
            .HasPostgresEnum("auth", "factor_status", new[] { "unverified", "verified" })
            .HasPostgresEnum("auth", "factor_type", new[] { "totp", "webauthn", "phone" })
            .HasPostgresEnum("auth", "one_time_token_type", new[] { "confirmation_token", "reauthentication_token", "recovery_token", "email_change_token_new", "email_change_token_current", "phone_change_token" })
            .HasPostgresEnum("realtime", "action", new[] { "INSERT", "UPDATE", "DELETE", "TRUNCATE", "ERROR" })
            .HasPostgresEnum("realtime", "equality_op", new[] { "eq", "neq", "lt", "lte", "gt", "gte", "in" })
            .HasPostgresExtension("extensions", "pg_stat_statements")
            .HasPostgresExtension("extensions", "pgcrypto")
            .HasPostgresExtension("extensions", "uuid-ossp")
            .HasPostgresExtension("graphql", "pg_graphql")
            .HasPostgresExtension("vault", "supabase_vault");

        modelBuilder.Entity<Document>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Document_pkey");

            entity.ToTable("Document");

            entity.HasIndex(e => e.CreatedBy, "Document_created_by_idx");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.Lists).HasColumnName("lists");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.Title)
                .HasDefaultValueSql("''::character varying")
                .HasColumnType("character varying")
                .HasColumnName("title");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Documents)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Document_created_by_fkey");
        });

        modelBuilder.Entity<DocumentList>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("DocumentList_pkey");

            entity.ToTable("DocumentList");

            entity.HasIndex(e => e.CreatedBy, "DocumentList_created_by_idx");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.ListItems).HasColumnName("list_items");
            entity.Property(e => e.Position)
                .HasDefaultValueSql("'0'::smallint")
                .HasColumnName("position");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.DocumentLists)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("DocumentList_created_by_fkey");
        });

        modelBuilder.Entity<DocumentListItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("ListItem_pkey");

            entity.ToTable("DocumentListItem");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Checked)
                .HasDefaultValue(false)
                .HasColumnName("checked");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Position)
                .HasDefaultValueSql("'0'::smallint")
                .HasColumnName("position");
            entity.Property(e => e.Text)
                .IsRequired()
                .HasDefaultValueSql("''::character varying")
                .HasColumnType("character varying")
                .HasColumnName("text");
        });

        modelBuilder.Entity<DocumentNote>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("DocumentNote_pkey");

            entity.ToTable("DocumentNote");

            entity.HasIndex(e => e.CreatedBy, "DocumentNote_created_by_idx");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.Position)
                .HasDefaultValueSql("'0'::smallint")
                .HasColumnName("position");
            entity.Property(e => e.Text)
                .IsRequired()
                .HasDefaultValueSql("''::character varying")
                .HasColumnType("character varying")
                .HasColumnName("text");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.DocumentNotes)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("DocumentNote_created_by_fkey");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Uaer_pkey");

            entity.ToTable("User", tb => tb.HasComment("Store main user data"));

            entity.HasIndex(e => e.Email, "Uaer_email_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("email");
            entity.Property(e => e.FirstName)
                .HasDefaultValueSql("''::character varying")
                .HasColumnType("character varying")
                .HasColumnName("first_name");
            entity.Property(e => e.LastName)
                .HasDefaultValueSql("''::character varying")
                .HasColumnType("character varying")
                .HasColumnName("last_name");
        });
        modelBuilder.HasSequence<int>("seq_schema_version", "graphql").IsCyclic();

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}