// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace xampl.Models.DTO;

public partial class Document
{
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    public string Title { get; set; }

    public List<int> Lists { get; set; }

    public List<int> Notes { get; set; }

    public virtual User CreatedByNavigation { get; set; }
}