// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace xampl.Models.DTO;

public partial class DocumentListItem
{
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Text { get; set; }

    public bool Checked { get; set; }

    public short Position { get; set; }

    public int CreatedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }
}