// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace xampl.Models.DTO;

/// <summary>
/// Store main user data
/// </summary>
public partial class User
{
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Email { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public virtual ICollection<DocumentListItem> DocumentListItems { get; set; } = new List<DocumentListItem>();

    public virtual ICollection<DocumentList> DocumentLists { get; set; } = new List<DocumentList>();

    public virtual ICollection<DocumentNote> DocumentNotes { get; set; } = new List<DocumentNote>();

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();
}